services:
  postgres:
    image: postgres:16
    container_name: webrat_postgres
    environment:
      POSTGRES_USER: webrat
      POSTGRES_PASSWORD: webrat
      POSTGRES_DB: webrat
    ports:
      - "5433:5432"
    volumes:
      - webrat_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: webrat_redis
    ports:
      - "6379:6379"
    volumes:
      - webrat_redis_data:/data

volumes:
  webrat_postgres_data:
  webrat_redis_data: